krayin/laravel-crm

packages/Webkul/Admin/src/Config/menu.php, packages/Webkul/Admin/src/Menu.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/email-tags.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/email.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/phone.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/tags.blade.php
=>  removed configuration section

README.md, database/seeders/DatabaseSeeder.php, packages/Webkul/Admin/src/Database/Seeders/DatabaseSeeder.php
=> readme and db-seeder updates

README.md, composer.json
> Updated composer.json and readme file for new project name
=> Updated composer.json and readme file for new project name

.github/ISSUE_TEMPLATE/1_Bug_report.md, .github/ISSUE_TEMPLATE/2_Feature_request.md, .github/ISSUE_TEMPLATE/3_Support_question.md, .github/ISSUE_TEMPLATE/4_Security_vulnerabilities.md, CODE_OF_CONDUCT.md, README.md, composer.json, packages/Webkul/Core/src/Console/Commands/Install.php, packages/Webkul/Core/src/Console/Commands/Version.php, packages/Webkul/User/composer.json
=> Update project name

README.md
=> demo link update

packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/compose.blade.php
=> Issue #issues fixed

README.md
Change logo background color in readme file
=> Change logo background color in readme file

packages/Webkul/Admin/src/Http/Controllers/User/ForgotPasswordController.php
=> Issue #79 fixed

packages/Webkul/Admin/src/Providers/ModuleServiceProvider.php, packages/Webkul/Attribute/src/Providers/ModuleServiceProvider.php, packages/Webkul/Contact/src/Providers/ModuleServiceProvider.php, packages/Webkul/Core/src/Console/Commands/Install.php, packages/Webkul/Core/src/Providers/BaseModuleServiceProvider.php, packages/Webkul/Core/src/Providers/ModuleServiceProvider.php, packages/Webkul/Email/src/Providers/ModuleServiceProvider.php, packages/Webkul/Lead/src/Providers/ModuleServiceProvider.php, packages/Webkul/Product/src/Providers/ModuleServiceProvider.php, packages/Webkul/Tag/src/Providers/ModuleServiceProvider.php, packages/Webkul/UI/src/Providers/ModuleServiceProvider.php, packages/Webkul/User/src/Providers/ModuleServiceProvider.php
=> Issue #32 fixed

packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php
=> Issue #63 fixed

composer.json, composer.lock, config/breadcrumbs.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Resources/views/mail/compose.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php, packages/Webkul/Admin/src/Resources/views/products/edit.blade.php, packages/Webkul/Admin/src/Resources/views/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/UI/src/Resources/assets/sass/app.scss, packages/Webkul/UI/src/Resources/views/datagrid/table.blade.php, routes/breadcrumbs.php
=> Issue #56 fixed

routes/breadcrumbs.php
Removed unnecessary breadcrumbs
=> Removed unnecessary breadcrumbs

routes/breadcrumbs.php
**BUGS:**
>Fixed null email subject issue of bradcrumbs
=> Fixed null email subject issue of bradcrumbs

app/Http/Kernel.php, composer.json, composer.lock, config/debugbar.php, packages/Webkul/Admin/src/Http/Middleware/Locale.php, storage/debugbar/.gitignore
=> Locale can be set from config

packages/Webkul/User/src/Database/Seeders/UsersSeeder.php
=> Issue #120 fixed

composer.json, config/app.php, config/concord.php, packages/Webkul/Activity/src/Contracts/Activity.php, packages/Webkul/Activity/src/Contracts/File.php, packages/Webkul/Activity/src/Database/Migrations/2021_05_12_150329_create_activities_table.php, packages/Webkul/Activity/src/Database/Migrations/2021_05_15_151855_create_activity_files_table.php, packages/Webkul/Activity/src/Models/Activity.php, packages/Webkul/Activity/src/Models/ActivityProxy.php, packages/Webkul/Activity/src/Models/File.php, packages/Webkul/Activity/src/Models/FileProxy.php, packages/Webkul/Activity/src/Providers/ActivityServiceProvider.php, packages/Webkul/Activity/src/Providers/ModuleServiceProvider.php, packages/Webkul/Activity/src/Repositories/ActivityRepository.php, packages/Webkul/Activity/src/Repositories/FileRepository.php, packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Activity/ActivityController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Lead/composer.json, packages/Webkul/Lead/src/Contracts/Activity.php, packages/Webkul/Lead/src/Contracts/File.php, packages/Webkul/Lead/src/Database/Migrations/2021_05_12_150329_create_lead_activities_table.php, packages/Webkul/Lead/src/Models/Lead.php, packages/Webkul/Lead/src/Providers/ModuleServiceProvider.php
=> Refactored activity code

packages/Webkul/Activity/composer.json, packages/Webkul/Admin/src/Http/Controllers/Setting/SourceController.php, packages/Webkul/Admin/src/Http/Controllers/Setting/TypeController.php
=> Issue #122 fixed

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/email.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/phone.blade.php
=> Issue #123 fixed

packages/Webkul/Admin/src/Traits/Dashboard/DataRetrival.php
Fixed issue in dashboard activity section
=> Fixed issue in dashboard activity section

packages/Webkul/Admin/src/Config/attribute_lookups.php, packages/Webkul/Admin/src/Config/datagrid_filters.php, packages/Webkul/Admin/src/Http/Controllers/Setting/AttributeController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/checkbox.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/lookup.blade1.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/multi-lookup.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/select.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/tags.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/view/checkbox.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/view/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/view/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/view/select.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php, packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
Improved lookup attribute type
=> Improved lookup attribute type

README.md
=> demo url update

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> #136 resolved

packages/Webkul/Admin/src/DataGrids/Setting/GroupDataGrid.php, packages/Webkul/Admin/src/Resources/lang/en/app.php
=> resolved #134

packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php
=> Issue #132 fixed

packages/Webkul/Admin/src/Http/Controllers/Setting/RoleController.php
=> Issue #133 fixed

packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php
=> Issue #135 fixed

packages/Webkul/Admin/src/Database/Seeders/AttributeSeeder.php, packages/Webkul/Admin/src/Http/Controllers/Product/ProductController.php
=> Issue #148 fixed

packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
=> Issue #152 fixed

packages/Webkul/Admin/src/Http/Controllers/Product/ProductController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/views/products/create.blade.php, packages/Webkul/Admin/src/Resources/views/products/index.blade.php, routes/breadcrumbs.php
=> Issue #147 fixed

packages/Webkul/Admin/src/Resources/views/contacts/organizations/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Resources/views/products/create.blade.php, packages/Webkul/Admin/src/Resources/views/products/edit.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php, packages/Webkul/Workflow/src/Providers/WorkflowServiceProvider.php
=> Issue #165 fixed

packages/Webkul/Admin/src/Exceptions/Handler.php, packages/Webkul/Admin/src/Http/Controllers/Setting/RoleController.php
=> Issue #172 fixed

packages/Webkul/UI/src/DataGrid/Traits/DatagridCollection.php
=> Issue #174 fixed

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/email.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/phone.blade.php, packages/Webkul/Attribute/src/Repositories/AttributeValueRepository.php
=> Issue #177 fixed

composer.lock, packages/Webkul/Admin/src/Http/Controllers/Contact/OrganizationController.php, packages/Webkul/Admin/src/Http/Controllers/Contact/PersonController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, routes/breadcrumbs.php
=> Issue #186 fixed

packages/Webkul/Admin/src/Config/datagrid_filters.php, packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/UI/src/DataGrid/DataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/DatagridCollection.php, packages/Webkul/UI/src/DataGrid/Traits/DatagridHelper.php
=> Issue #208 fixed

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Issue #204 fixed

packages/Webkul/Admin/src/Config/core_config.php, packages/Webkul/Admin/src/Http/Middleware/Locale.php, packages/Webkul/Workflow/src/Providers/WorkflowServiceProvider.php
=> Fixed #199

packages/Webkul/Admin/src/Traits/Dashboard/DataRetrival.php, packages/Webkul/Admin/src/Traits/Dashboard/Helper.php
=> Issue #197 fixed

.env.example, CHANGELOG for v1.x.x.md
**BUGS:**
>Updated changelog file
=> Updated changelog file

packages/Webkul/Admin/src/Http/Controllers/Contact/OrganizationController.php, packages/Webkul/Admin/src/Http/Controllers/Contact/PersonController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php
=> Issue #225 fixed

packages/Webkul/Admin/src/Resources/views/settings/users/create.blade.php
=> Issue #226 fixed

packages/Webkul/Admin/src/Exceptions/Handler.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php
=> Issue #217 fixed

config/flare.php, config/ignition.php, docker/7.4/Dockerfile, docker/8.0/Dockerfile, docker/8.0/php.ini, packages/Webkul/Core/src/Config/concord.php, packages/Webkul/Core/src/Console/Commands/Install.php
=> Issue #230 fixed

packages/Webkul/Admin/src/DataGrids/Setting/AttributeDataGrid.php
=> Issue #173 fixed

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
=> Issue #194 fixed

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/create.blade.php, packages/Webkul/Admin/src/Resources/views/leads/list/kanban.blade.php, packages/Webkul/Admin/src/Resources/views/leads/list/table.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php, packages/Webkul/Admin/src/Resources/views/products/create.blade.php, packages/Webkul/Admin/src/Resources/views/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/email-templates/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/email-templates/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/groups/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/groups/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/sources/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/types/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/index.blade.php, routes/breadcrumbs.php
=> Updated translations

README.md
Remove the whitespace to make the text bold
=> Remove the whitespace

packages/Webkul/Admin/src/Http/Controllers/Contact/PersonController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php
Imports are wrong and not needed.
=> Remove wrong imports

packages/Webkul/Email/src/Helpers/Charset.php
Flattens the code by removing extra `else`
=> Flattens code

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php
=> Issue #251 fixed

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit.blade.php
=> Issue #257 fixed

packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Issue #260 fixed

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Issue #255 fixed

packages/Webkul/UI/src/DataGrid/DataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
- Moved one method for having all collections of methods sorted.
=> Moved one method for having all collections of methods sorted

packages/Webkul/Admin/src/Resources/views/leads/list/kanban.blade.php
=> Full Height Added

packages/Webkul/Admin/src/Database/Seeders/AttributeSeeder.php, packages/Webkul/Admin/src/Http/Controllers/Setting/GroupController.php, packages/Webkul/Contacts/src/Database/Migrations/2021_09_22_194103_add_unique_index_to_name_in_organizations_table.php, packages/Webkul/User/src/Database/Migrations/2021_09_22_194622_add_unique_index_to_name_in_groups_table.php
**BUGS:**
>Issues #272, #270 fixed
=> Issues #272, #270 fixed

packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Issue #263 fixed

packages/Webkul/Admin/src/Helpers/Dashboard.php
Dashboard top products issues fixed
=> Dashboard top products issues fixed

packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php
=> Issue #285 fixed

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/multi-lookup.blade.php
=> Issue #287 fixed

packages/Webkul/Admin/src/Http/Controllers/Setting/UserController.php, packages/Webkul/Admin/src/Resources/views/settings/users/edit.blade.php
=> Issue #298 fixed

packages/Webkul/Admin/publishable/assets/images/error-illustraton.svg, packages/Webkul/Admin/src/Resources/assets/images/error-illustraton.svg, packages/Webkul/Admin/src/Resources/views/errors/401.blade.php, packages/Webkul/Admin/src/Resources/views/errors/403.blade.php, packages/Webkul/Admin/src/Resources/views/errors/404.blade.php, packages/Webkul/Admin/src/Resources/views/errors/419.blade.php, packages/Webkul/Admin/src/Resources/views/errors/429.blade.php, packages/Webkul/Admin/src/Resources/views/errors/500.blade.php, packages/Webkul/Admin/src/Resources/views/errors/503.blade.php, packages/Webkul/Admin/src/Resources/views/errors/illustrated-layout.blade.php, resources/views/errors/401.blade.php, resources/views/errors/403.blade.php, resources/views/errors/404.blade.php, resources/views/errors/419.blade.php, resources/views/errors/429.blade.php, resources/views/errors/500.blade.php, resources/views/errors/503.blade.php, resources/views/errors/illustrated-layout.blade.php
=> Designed error pages

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, resources/views/errors/401.blade.php, resources/views/errors/403.blade.php, resources/views/errors/404.blade.php, resources/views/errors/419.blade.php, resources/views/errors/429.blade.php, resources/views/errors/500.blade.php, resources/views/errors/503.blade.php, resources/views/errors/illustrated-layout.blade.php
Link: https://github.com/krayin/laravel-crm/issues/301#issuecomment-928887892
=> Added Alias And Searchable Key #301#issuecomment-928887892

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Activity/ActivityController.php, packages/Webkul/Admin/src/Http/routes.php
Link: https://github.com/krayin/laravel-crm/issues/313
=> Activities mass delete added #313

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-action.blade.php
=> Issue #319 fixed

packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php
=> Issue #138 fixed

packages/Webkul/UI/src/DataGrid/Traits/ProvideCollection.php, packages/Webkul/UI/src/Resources/lang/en/app.php
Link: https://github.com/krayin/laravel-crm/issues/325
=> Mail view issue fixed #325

packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Issue #334 fixed

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
Link: https://github.com/krayin/laravel-crm/issues/282
=> Height Adjusted #282

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideCollection.php
Link 1: https://github.com/krayin/laravel-crm/issues/306
Link 2: https://github.com/krayin/laravel-crm/issues/318
Link 3: https://github.com/krayin/laravel-crm/issues/338
- Date range filter added.
- Attachment icon remove.
=> Date range filter added and icon removed #306, #338 and #318

packages/Webkul/UI/src/DataGrid/Traits/ProvideCollection.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideQueryResolver.php
Link: https://github.com/krayin/laravel-crm/issues/283
=> Date range filter improved #283

packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
Link: https://github.com/krayin/laravel-crm/issues/309
=> Fixed date filters #309

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
Link: https://github.com/krayin/laravel-crm/issues/341
=> Searchable key added #341

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Username exception fixed

packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
Link: https://github.com/krayin/laravel-crm/issues/354
=> Duration date fixed #354

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
Link: https://github.com/krayin/laravel-crm/issues/280#event-5384884578
=> Key added #280#event-5384884578

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/Admin/src/DataGrids/Contact/OrganizationDataGrid.php, packages/Webkul/Admin/src/DataGrids/Contact/PersonDataGrid.php, packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/Admin/src/DataGrids/Product/ProductDataGrid.php, packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/AttributeDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/EmailTemplateDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/GroupDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/RoleDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/SourceDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/TagDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/TypeDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/UserDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/WorkflowDataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideCollection.php
Link: https://github.com/krayin/laravel-crm/issues/363
=> Default case added #363

packages/Webkul/Attribute/src/Traits/CustomAttribute.php
=> Issue #364 fixed

packages/Webkul/Admin/src/DataGrids/Setting/TagDataGrid.php
=> Issue #369 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
=> Tab Filters Enhanced

packages/Webkul/Admin/src/DataGrids/Setting/AttributeDataGrid.php
=> [Fixed: #367 filter Attributes by type.]

packages/Webkul/Admin/src/DataGrids/Setting/TagDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Setting/TagController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/settings/tags/edit.blade.php, routes/breadcrumbs.php
**BUGS:**
There should be a option to edit the tag #368
[Implement: #368 Option to edit the tag.]
=> [Implement: #368 Option to edit the tag.]

packages/Webkul/Admin/src/DataGrids/Setting/TagDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Setting/TagController.php, packages/Webkul/Admin/src/Http/routes.php
**BUGS:**
[Implemented: #372 Option to delete the multiple tags.]
=> [Implemented: #372 Option to delete the multiple tags.]

packages/Webkul/Admin/src/Http/Controllers/Contact/PersonController.php
**BUGS:**
[Fixed: #380 The person should be received mail, after delete person.]
=> [Fixed: #380 The person should be received mail, after delete person.]

packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php
**BUGS:**
[Fixed: #337 Page should be redirect to inbox. after send mail.]
=> [Fixed: #337 Page should be redirect to inbox. after send mail.]

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php
Link: https://github.com/krayin/laravel-crm/issues/404
=> Created by filter fixed #404

.gitignore
Add DS_Store to gitignore for Mac support
=> Add DS_Store to gitignore for Mac support

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/email.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/phone.blade.php
=> Issue #620 fixed

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/table.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/view-swither.blade.php
=> Issue #511 fixed

packages/Webkul/Admin/src/Resources/views/leads/view/activity-action.blade.php, packages/Webkul/Admin/src/Resources/views/mail/compose.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Issue #453 fixed

packages/Webkul/Admin/src/Database/Seeders/AttributeSeeder.php, packages/Webkul/Attribute/src/Http/Requests/AttributeForm.php, packages/Webkul/Attribute/src/Repositories/AttributeValueRepository.php, packages/Webkul/Contact/src/Repositories/PersonRepository.php
=> Issue #308 fixed

packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
=> Issue #634 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Issue #635 fixed

packages/Webkul/Admin/src/Helpers/Dashboard.php
=> Issue #636 fixed

packages/Webkul/Admin/src/DataGrids/Contact/OrganizationDataGrid.php
=> Issue #637 fixed

packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php
=> Issue #639 fixed

packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Issue #638 fixed

packages/Webkul/Admin/src/Resources/views/leads/view/stage.blade.php
=> Issue #647 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Issue #648 fixed

packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php
=> Add placeholder on contact person

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php
=> Issue #596 fixed

packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php
=> Issue #582 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Issue #496 fixed

packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php
=> Issue #373 fixed

packages/Webkul/Admin/src/Helpers/Dashboard.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
=> Issue #343 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/Resources/lang/en/app.php
Link: https://github.com/krayin/laravel-crm/issues/572
=> Added Tags In Leads #572

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
Link: https://github.com/krayin/laravel-crm/issues/572#issuecomment-964814068
=> Duplicate Issue Fixed #572#issuecomment-964814068

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Lead/src/Models/Lead.php
**BUGS:**
>Rotten days issue fixed
=> Rotten days issue fixed

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
- Rotten day synced with the table view.
=> Rotten day synced with the table view

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php, packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Traits/ProvideDropdownOptions.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideCollection.php
Link 1: https://github.com/krayin/laravel-crm/issues/668
Link 2: https://github.com/krayin/laravel-crm/issues/671
=> Tab Filter, Group By And Options Fixed #668

packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php
=> Issue #672 fixed

packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Admin/DashboardController.php
=> Isue #672 fixed

packages/Webkul/Lead/src/Database/Migrations/2021_11_11_180804_change_lead_pipeline_stage_id_constraint_in_leads_table.php
=> Issue #678 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Issue #679 fixed

packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Removed unreached code

packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php, packages/Webkul/Lead/src/Repositories/PipelineRepository.php
**BUGS:**
>Issue #308 fixed
>Issue #678 fixed
=> Issues fixed

packages/Webkul/Admin/src/Http/Controllers/Activity/ActivityController.php, packages/Webkul/Admin/src/Http/Controllers/Contact/OrganizationController.php, packages/Webkul/Admin/src/Http/Controllers/Contact/PersonController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/QuoteController.php, packages/Webkul/Admin/src/Http/Controllers/Lead/TagController.php, packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Http/Controllers/Product/ProductController.php, packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php, packages/Webkul/Workflow/src/Helpers/Entity/AbstractEntity.php, packages/Webkul/Workflow/src/Helpers/Entity/Activity.php, packages/Webkul/Workflow/src/Helpers/Entity/Lead.php, packages/Webkul/Workflow/src/Helpers/Entity/Person.php, packages/Webkul/Workflow/src/Helpers/Entity/Quote.php, packages/Webkul/Workflow/src/Listeners/Entity.php
=> Issue #685 fixed

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php
=> Issue #692 fixed

.env.example, CHANGELOG for v1.x.x.md
=> Changelog updated

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Lead/src/Models/Lead.php, packages/Webkul/Lead/src/Repositories/LeadRepository.php
=> Issue #699 fixed

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php
=> Issue #700 fixed

packages/Webkul/Admin/src/Helpers/Dashboard.php
=> Issue #704 fixed

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Issue #701 fixed

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Resources/views/activities/index/table.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-action.blade.php
=> Issue #709 fixed

packages/Webkul/Admin/src/Resources/views/leads/view/stage.blade.php
=> Issue #712 fixed

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-action.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php, packages/Webkul/Workflow/src/Helpers/Entity/Activity.php
=> Issue #720 fixed

packages/Webkul/Admin/src/Http/Controllers/Setting/AttributeController.php
=> Issue #723 fixed

packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
=> Add asterisk icon in Quote ite

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/textarea.blade.php
- v-pre added for avoiding the vue to get parse.
=> V Pre Added

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php, packages/Webkul/Lead/src/Repositories/LeadRepository.php
**BUGS:**
Fixed issue  #679 in kanban view
=> Fixed issue #679in kanban view

packages/Webkul/Admin/src/Helpers/Dashboard.php
=> Issue #719 fixed

packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
=> Issue #722 fixed

packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Issue #724 fixed

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php
=> Issue #735 fixed

packages/Webkul/UI/src/Resources/views/export/temp.blade.php
- Removed preg match, all special chars should be handled at the time of validations and insertion in the database.
=> Pregmatch Removed

packages/Webkul/UI/src/DataGrid/DataGrid.php, packages/Webkul/UI/src/DataGrid/Traits/ProvideExport.php, packages/Webkul/UI/src/Resources/views/export/temp.blade.php
- Exactly the same will come to export which is mentioned in the tables.
=> JSON Handled Export Feature

packages/Webkul/Activity/src/Models/Activity.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php
=> Issue #710 fixed

packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php, packages/Webkul/Admin/src/Resources/lang/ar/ar.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
Fixed issue : https://github.com/krayin/laravel-crm/issues/698
=> Fixed issue #698

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
**Fixed issue**: https://github.com/krayin/laravel-crm/issues/692
=> Fixed issue #692

README.md
Update **README.md**  file
Add command for **route cache clear**
=> Add route command for Route cache cleare

packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Http/Controllers/Setting/UserController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/lang/ar/ar.php, packages/Webkul/Admin/src/Resources/lang/en/app.php
=> Issue #435 fixed

packages/Webkul/Attribute/src/Http/Requests/AttributeForm.php
=> Issue #755 fixed

.env.testing, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php, tests/Feature/AuthenticationTest.php
=> Logout method changed

packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
**Fixed bug :** https://github.com/krayin/laravel-crm/issues/777
=> Fixed issue #777

packages/Webkul/Attribute/src/Http/Requests/AttributeForm.php
=> Issue #774 fixed

packages/Webkul/Admin/src/Resources/views/layouts/nav-left.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/stage.blade.php
=> Issue #788 fixed

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/file.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/image.blade.php
=> Issue #794 fixed

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/common/custom-attributes/view.blade.php
=> V-Pre Added #785

packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
- Removed image when not needed.
=> Removed image when not needed

packages/Webkul/WebForm/src/Http/Controllers/WebFormController.php, packages/Webkul/WebForm/src/Repositories/WebFormRepository.php, packages/Webkul/WebForm/src/Resources/views/settings/web-forms/edit.blade.php, packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js.blade.php, packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
**BUGS:**
>Issue #823 fixed
> Issue #822 fixed
=> Issues #823, #822 fixed

packages/Webkul/WebForm/src/Providers/WebFormServiceProvider.php
=> Issue #823 fixed

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php
=> Fixed issue #824

packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
=> Fixed issue #830

packages/Webkul/WebForm/src/Resources/lang/ar/app.php, packages/Webkul/WebForm/src/Resources/lang/en/app.php
=>  Fixed issue #868

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
=> Fixed issue #858

packages/Webkul/WebForm/src/Resources/lang/ar/app.php
=> Fixed issue #853

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=>  fixed issu #866

packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
Link: [#874](https://github.com/krayin/laravel-crm/issues/874)
=> Able to customise web-form colors

packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php
=> Update-missing code

packages/Webkul/Core/src/Config/concord.php, packages/Webkul/Core/src/Config/cors.php, packages/Webkul/Core/src/Providers/CoreServiceProvider.php
- These are publishable updated in the core so should be added in config as well.
=> Cors And Concord File

packages/Webkul/WebForm/src/Http/Controllers/WebFormController.php
The form wasn't enable to be submitted by an non login users unless I remove line 302. Hope any other solution will occur also.
**BUGS:**
=> Form can be submitted just by logged in users

packages/Webkul/Admin/src/Resources/lang/tr/app.php
=> Fixed issue #919

packages/Webkul/Admin/src/Resources/lang/ar/app.php
Complete some missing translation on Arabic
=> Complete missing translation on Arabic

packages/Webkul/Admin/src/Resources/lang/tr/app.php
complete missing translation in turkish
=> complete missing translation

packages/Webkul/Admin/src/Helpers/Dashboard.php
=> Translate leads-over time

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/views/leads/view/activity-list.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
**BUGS:**
#965
>Translation issue while deleting the mail
=> Fixed issue #965

packages/Webkul/WebForm/src/Resources/views/settings/web-forms/create.blade.php
**BUGS:**
**Fixed:**  https://github.com/krayin/laravel-crm/issues/825
> Remove disable attribute from web-form  attributes
=> Fixed: #825

packages/Webkul/Admin/src/Helpers/Dashboard.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
**BUGS:**
Fixed: https://github.com/krayin/laravel-crm/issues/846
>Fixed Dashboard Translation issues
=> Fixed Issue : #846

packages/Webkul/Admin/src/Http/Controllers/Setting/UserController.php
**BUGS:**
https://github.com/krayin/laravel-crm/issues/961
>Exception while creating the user
=>  Fixed issue #961

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php
**BUGS:**
https://github.com/krayin/laravel-crm/issues/968
>Translate Activities in activity-table
=> Fixed issue : #968

packages/Webkul/Admin/src/Resources/views/sessions/login.blade.php
**BUGS:**
#924 
>Auto focus added on mails input box  login user
=> Fixed issue: #924

packages/Webkul/Admin/src/Resources/lang/tr/app.php
**BUGS:**
#974 
>Turkish translation added for account section
=> Fixed issue: #976

packages/Webkul/Admin/src/Resources/lang/ar/app.php
Complete missing translations for Arabic locale
=> Translation ussues

packages/Webkul/Admin/src/Resources/views/settings/pipelines/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/pipelines/edit.blade.php
**require class added for pipeline stage**
=> require class added for pipeline stage

packages/Webkul/Admin/src/Http/Controllers/User/AccountController.php, packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
**BUGS:**
> Steps to Reproduce:
> Step 1: Visit above vulnerable url and upload a svg file containg payload at upload a profile image
option.
> Step 2: Now to execute the payload click on view image. Payload should gets execute. 
Is Fixed now.
https://demo.krayincrm.com/krayincrm-103-80-65-178/admin/account/update
=> authenticated xss via file upload issue

packages/Webkul/Activity/src/Repositories/ActivityRepository.php
=> Issue #1020 fixed

packages/Webkul/Admin/src/Config/acl.php
**BUGS:**
#1021
> Complete some corrections on the acl.php file.
=> Issue #1021 fixed

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
**BUGS:**
#815
>Now file will be uploaded successfully
=> Issue #815 fixed

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
**BUGS:**
#282 
>**drag-container** class added
=> Issue #282 fixed

packages/Webkul/Admin/src/Http/Controllers/Admin/DashboardController.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
**BUGS:**
#1032 
> Add condition for text attribute
=> Issue #1032 fixed

packages/Webkul/Admin/src/DataGrids/Contact/PersonDataGrid.php, packages/Webkul/UI/src/Resources/views/export/temp.blade.php
=> Issue #899 fixed

packages/Webkul/WebForm/src/Http/Controllers/WebFormController.php
=> Issue #950 Fixed

packages/Webkul/Admin/src/Http/Middleware/Locale.php, packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
=> Fixed #1055 and removed top navigation locale management

CHANGELOG for v1.x.x.md
=> ChangeLog updated for V1.2.3

packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
**BUGS:**
#1085
>Astrics icon added for permission type
=> Issue #1085 fixed

packages/Webkul/Admin/src/Menu.php
removed some line of code due to no use.
=> Removed unwanted changes

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Fixed #435

packages/Webkul/WebForm/src/Resources/lang/ar/app.php, packages/Webkul/WebForm/src/Resources/lang/en/app.php, packages/Webkul/WebForm/src/Resources/lang/tr/app.php, packages/Webkul/WebForm/src/Resources/views/settings/web-forms/edit.blade.php
**BUGS:**
#974
> **Copy option** added for embed **web-form**
=> Enhancement #974 done

packages/Webkul/Admin/src/Helpers/Dashboard.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
**BUGS:**
#1073 
>fix link view issue
and make it compatible for index lead
=> Issue #1073 fixed

packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js.blade.php, packages/Webkul/WebForm/src/Resources/views/settings/web-forms/form-js/form.blade.php
=> Issue #847 fixed

packages/Webkul/UI/src/DataGrid/Traits/ProvideTabFilters.php
=> Fixed #1091

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
**BUGS:**
#1088 
> Fix mail lead view issue
=> Issue #1088 Fixed

composer.json, config/app.php, packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php, packages/Webkul/UI/src/Resources/lang/en/app.php
**BUGS:**
#663 
>Implement print feature for a quote and fix pdf issue for laravel 9
=> Issue #663 fixed

CHANGELOG for v1.x.x.md
=> Changelog-Updated

packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php, packages/Webkul/Workflow/src/Helpers/Entity/Lead.php
=> Fixed #947

packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
=> Fixed #1115

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
=> bug: Duplicate cards on Kanban view after search #1152

packages/Webkul/Admin/src/Http/routes.php
Added throttle middleware in the person's destroy route
=> Added rate limit in person's destroy route

packages/Webkul/Admin/src/Resources/views/quotes/pdf.blade.php
issue described here https://github.com/krayin/laravel-crm/issues/1240
=> fixed #1240

composer.lock
=> Fixed #1215

packages/Webkul/Admin/src/DataGrids/Setting/UserDataGrid.php, packages/Webkul/Admin/src/Resources/assets/js/app.js, packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
issue explained here https://github.com/krayin/laravel-crm/issues/1214
=> Fixed #1214

packages/Webkul/UI/src/Resources/lang/ar/app.php, packages/Webkul/UI/src/Resources/lang/en/app.php, packages/Webkul/UI/src/Resources/lang/es/app.php, packages/Webkul/UI/src/Resources/lang/fa/app.php, packages/Webkul/UI/src/Resources/lang/tr/app.php
=> Fix Issue #1139

packages/Webkul/Admin/src/DataGrids/Contact/PersonDataGrid.php, packages/Webkul/Admin/src/DataGrids/Setting/UserDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Setting/UserController.php
=> Issue #1196 fixed.

packages/Webkul/UI/src/Resources/lang/ar/app.php, packages/Webkul/UI/src/Resources/lang/en/app.php, packages/Webkul/UI/src/Resources/lang/es/app.php, packages/Webkul/UI/src/Resources/lang/fa/app.php, packages/Webkul/UI/src/Resources/lang/tr/app.php
=> Issue #1139 fixed.

packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Email/src/Repositories/EmailRepository.php
=> Issue #1198 fixed.

packages/Webkul/Installer/src/Console/Commands/Installer.php
Add publish command into installer.
=> Add publish command into installer.

packages/Webkul/Activity/src/Models/Activity.php
fix issue while save activity.
=> fix issue while save activity.

packages/Webkul/Installer/src/Console/Commands/Installer.php, packages/Webkul/Installer/src/Listeners/Installer.php, packages/Webkul/Installer/src/Providers/InstallerServiceProvider.php
=> Installer fixes

packages/Webkul/Admin/src/Resources/views/layouts/master.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php, packages/Webkul/Admin/src/Resources/views/settings/tags/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/user/account/edit.blade.php
=> update push directive.

.github/workflows/linting_tests.yml, composer.json, composer.lock, pint.json
=> pint setup.

packages/Webkul/Admin/src/Http/Controllers/User/ForgotPasswordController.php, packages/Webkul/Admin/src/Http/routes.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php, packages/Webkul/Admin/src/Resources/views/sessions/forgot-password.blade.php, packages/Webkul/Admin/src/Resources/views/sessions/login.blade.php, packages/Webkul/Admin/src/Resources/views/sessions/reset-password.blade.php, packages/Webkul/Admin/src/Routes/auth-routes.php, packages/Webkul/Admin/src/Routes/web.php
=> Updated Login, Forget password, Reset Password Pages

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/inline.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
=> add inline component.

packages/Webkul/Admin/src/Resources/views/components/attachments/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/edit.blade.php
=> attachement.

packages/Webkul/Admin/src/Resources/views/components/lookup/index.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/index.blade.php
=> Add lookup component.

packages/Webkul/Admin/src/DataGrids/Contact/PersonDataGrid.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/mass-action.blade.php
=> Massaction UI

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php
=> Attribute index page

packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
**BUGS:**
Update the ui of workflow.
=> Update the ui of workflow.

packages/Webkul/Admin/src/Resources/views/components/media/images.blade.php
**BUGS:**
Fix image component.
=> Fix image component.

packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
**BUGS:**
Quote and lead automatic fill amount.
=> Quote and lead automatic fill amount.

packages/Webkul/Admin/src/Resources/views/components/tinymce/index.blade.php
**BUGS:**
Fix tinymce was not showing when toggle the editor.
=> fix tinymce was not showing when toggle the editor.

packages/Webkul/Admin/src/Config/acl.php, packages/Webkul/Admin/src/Http/Controllers/Lead/TagController.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Routes/leads-routes.php
=> Tags completed

packages/Webkul/Admin/src/Resources/views/components/attributes/view.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/view/price.blade.php
**BUGS:**
Changes to attribute inline edit
=> Changes to attribute inline edit

packages/Webkul/Admin/src/Resources/views/components/attributes/view.blade.php
**BUGS:**
Fixed alignment issue in attributes view
=> Fixed alignment issue in attributes view

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/Controllers/Products/ProductController.php, packages/Webkul/Admin/src/Http/Resources/ProductResource.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/lookup/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php, packages/Webkul/Admin/src/Resources/views/leads/create.blade.php, packages/Webkul/Admin/src/Resources/views/leads/edit.blade.php, packages/Webkul/Admin/src/Routes/leads-routes.php, routes/breadcrumbs.php
=> Added lead edit page and update lead create page ui

packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
**BUGS:**
fix quotes creation and updation.
=> fix quotes creation and updation.

packages/Webkul/Admin/src/Routes/activities-routes.php, packages/Webkul/Admin/src/Routes/auth-routes.php, packages/Webkul/Admin/src/Routes/configuration-routes.php, packages/Webkul/Admin/src/Routes/contacts-routes.php, packages/Webkul/Admin/src/Routes/leads-routes.php, packages/Webkul/Admin/src/Routes/mail-routes.php, packages/Webkul/Admin/src/Routes/products-routes.php, packages/Webkul/Admin/src/Routes/quote-routes.php, packages/Webkul/Admin/src/Routes/rest-routes.php, packages/Webkul/Admin/src/Routes/settings-routes.php
=> Fixed exceptions in login page(middleware issue)

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php, packages/Webkul/Admin/src/Resources/assets/css/app.css, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/leads.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/persons.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/products.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/header/mega-search/quotes.blade.php, packages/Webkul/Admin/src/Routes/quote-routes.php
=> Update mega search

packages/Webkul/Admin/src/Config/menu.php, packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
=> mail index page.

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/components/lookup/index.blade.php
=> Fix exceptions

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php
**BUGS:**
Fixed minor activity emplty placeholders issue
=> Fixed minor activity emplty placeholders issue

packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Http/Controllers/Mail/EmailController.php, packages/Webkul/Admin/src/Http/Controllers/Products/ProductController.php, packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php, packages/Webkul/Admin/src/Http/Resources/QuoteResource.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/address.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/boolean.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/date.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/datetime.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/email.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/image.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/phone.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php, packages/Webkul/Admin/src/Routes/leads-routes.php, packages/Webkul/Lead/src/Models/Lead.php, packages/Webkul/Product/src/Repositories/ProductRepository.php, packages/Webkul/Quote/src/Repositories/QuoteRepository.php
**BUGS:**
refactor email view page and fix inline ui issues.
=> refactor email view page and fix inline ui issues.

packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php
**BUGS:**
Fixed Table in Product view
=> Fixed Table in Product view

packages/Webkul/Admin/src/Resources/views/components/attributes/view/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/lookup.blade.php
=> refactor the person page.

packages/Webkul/Admin/src/Resources/views/contacts/persons/view.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, routes/breadcrumbs.php
**BUGS:**
View pages breadcrums fixed
=> View pages breadcrums fixed

packages/Webkul/Admin/src/Resources/assets/css/app.css, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Routes/settings-routes.php
=> fix mail datagrid.

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-sources.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-types.blade.php
**BUGS:**
>Dashboard empty placeholders added
=> Dashboard empty placeholders added

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/pipelines/kanban.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/pipelines/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/pipelines/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/locations.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/webhook/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/webhook/edit.blade.php
**BUGS:**
Fix minor  issues and dark mode and ltr
=> Fix minor  issues and dark mode and ltr

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php, packages/Webkul/Admin/src/Resources/views/components/tree/view.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban/filter.blade.php
=> FIxed icon issue

packages/Webkul/Admin/src/DataGrids/Contact/OrganizationDataGrid.php, packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php, packages/Webkul/Admin/src/Resources/views/leads/index/table.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/view-switcher.blade.php
=> Fixed ui issues

packages/Webkul/Admin/src/Resources/views/components/shimmer/leads/index/kanban.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/view-switcher.blade.php
=> fixed issue #1424

packages/Webkul/Admin/src/Http/Controllers/Activity/ActivityController.php
https://github.com/krayin/laravel-crm/issues/1433
=> fix: #1433 note issue

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/leads/view/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> mail view page.

packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> fix #1403 fixed.

packages/Webkul/Admin/src/DataGrids/Settings/WarehouseDataGrid.php
https://github.com/krayin/laravel-crm/issues/1445
=> fix: warehouse product issue

packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
=> Issue #1418 fixed.

packages/Webkul/Installer/src/Console/Commands/Installer.php
=> Issue #1450 fixed.

packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
=> Issue #1421 fixed.

packages/Webkul/Admin/src/Http/Controllers/Contact/Persons/PersonController.php
=> Issue #1459 fixed.

packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/address.blade.php
fix validation into the address component.
=> fix validation into the address component.

packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php
**BUGS:**
>Fix product inventory console error.
=> fix product inventory console error.

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php
=> Tag translation

packages/Webkul/Product/src/Models/Product.php
**BUGS:**
fix warehouse modal name.
=> fix warehouse modal name.

packages/Webkul/Admin/src/Resources/views/leads/view/person.blade.php
**BUGS:**
>add mailto and callto to leads contact person.
=> add mailto and callto to leads contact person.

packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php
=> fix sidebar.

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban/filter.blade.php
**BUGS:**
>fix datagrid of leads.
=> fix datagrid of leads.

packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/locations.blade.php
=> Issue #1481 fixed.

packages/Webkul/Admin/src/Resources/views/components/activities/actions/activity.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/mail.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/note.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php
=> Issue #1477 fixed.

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/email.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/phone.blade.php
=> Issue #1415 fixed.

packages/Webkul/Admin/src/Resources/views/components/table/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/tbody/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/tbody/tr.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/td.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/thead/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/table/thead/tr.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/products.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/quotes.blade.php, packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/locations.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
=> Table component

packages/Webkul/Admin/src/Resources/views/components/activities/actions/activity.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/mail.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/note.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
=> Activity actions

packages/Webkul/Admin/src/DataGrids/Settings/TagDataGrid.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php
**BUGS:**
>fix settings tags view create and update.
=> fix settings tags view create and update.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/quotes.blade.php
**BUGS:**
>fix inline select box tooltip and minor issue in leads view page while navigating the custom activity tabs
=> fix inline select box tooltip and minor issue in leads view page while navigating the custom activity tabs

packages/Webkul/Admin/src/Resources/views/leads/edit.blade.php
=> Issue#1503

packages/Webkul/Admin/src/Helpers/Reporting/Lead.php
=> Issue #1502 fixed

packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
=> Issue #1486 fixed.

packages/Webkul/Attribute/src/Repositories/AttributeValueRepository.php
**BUGS:**
>remove checks form save method.
=> remove checks form save method.

packages/Webkul/Product/src/Models/Product.php
**BUGS:**
>Update product modal location.
=> Update product modal location.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php, packages/Webkul/Admin/src/Resources/views/components/tags/index.blade.php
**BUGS:**
>fix inline padding issue
=> fix inline padding issue

composer.json, composer.lock, packages/Webkul/Admin/src/Http/Controllers/Quote/QuoteController.php, packages/Webkul/Core/src/Traits/PDFHandler.php
**BUGS:**
>pdf handle added to core.
=> pdf handle added to core.

packages/Webkul/Activity/src/Traits/LogsActivity.php, packages/Webkul/Admin/src/Resources/views/leads/view/stages.blade.php
=> fix leads stages.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/address.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/boolean.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/date.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/datetime.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/email.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/phone.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php
**BUGS:**
>Inline component value label.
=> Inline component value label.

packages/Webkul/Activity/src/Traits/LogsActivity.php
**BUGS:**
>update activity log traits.
=> update activity log traits.

packages/Webkul/Admin/src/Resources/views/components/activities/actions/activity.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/mail.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/note.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/view.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Resources/views/products/view.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view.blade.php
**BUGS:**
>View actions and sticky the right bar.
=> View actions and sticky the right bar.

packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
=> fix workflow.

packages/Webkul/Automation/src/Helpers/Validator.php
Fix validation attribtues with enums.
=> Fix validation attribtues with enums.

packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php
=> Issue #1521 fixed.

packages/Webkul/Admin/src/Resources/views/dashboard/index/open-leads-by-states.blade.php
=> Issue #1528 fixed

packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/locations.blade.php
=> Issue #1520 fixed

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php
=> Issue #1482 fixed.

packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php
=> Issue #1485 has been fixed.

packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
=> Issue #1541 fixed.

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php
=> Issue #1545 fixed.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/control.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/stages.blade.php
=> leads stages date.

packages/Webkul/Admin/src/Resources/views/settings/webhook/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/webhook/edit.blade.php, packages/Webkul/Automation/src/Helpers/Entity/AbstractEntity.php
=> automation entity.

packages/Webkul/Admin/src/Http/Controllers/User/ForgotPasswordController.php
=> issue#1550 fixed.

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php
=> Issue #1533 fixed.

packages/Webkul/Admin/src/Resources/views/settings/web-forms/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/edit.blade.php
=> Issue #1527 fixed.

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php
add description to leads view page.
=> add description to leads view page.

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/table.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/products/index.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/attributes/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/email-templates/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/pipelines/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/sources/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/types/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/webhook/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/index.blade.php
=> fix datagrid shimmer effects

packages/Webkul/Admin/src/Routes/Admin/mail-routes.php
=> add missing mail route.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/address.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/boolean.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/date.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/datetime.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/email.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/image.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/multiselect.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/phone.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php
add emitter to inline component on error.
=> add emitter to inline component on error.

packages/Webkul/Admin/src/Resources/views/components/layouts/sidebar/index.blade.php
=> sidebar menu width fixed.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/address.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/email.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/phone.blade.php
=> Move to Body Teleport.

app/Http/Kernel.php, packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/lookup/index.blade.php
fix lookup component and add Convert empty string to null middleware.
=> fix lookup component and add Convert empty string to null middleware.

packages/Webkul/Product/src/Database/Migrations/2024_06_28_154009_create_product_inventories_table.php, packages/Webkul/Product/src/Database/Migrations/2024_09_06_065808_alter_product_inventories_table.php
product inventories migration updated.
=> product inventories migration updated.

packages/Webkul/Admin/src/Resources/views/components/layouts/index.blade.php
=> Update the layout page.

packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-sources.blade.php, packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-types.blade.php
=> fix donut chart ui.

packages/Webkul/Admin/src/Resources/views/leads/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
=> fix workflow ui.

packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> Issue #1578 fixed

packages/Webkul/Admin/src/Resources/views/settings/webhook/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/webhook/edit.blade.php
=> Issue #1603 fixed.

packages/Webkul/Admin/src/Http/Resources/ActivityFileResource.php
Add url to attribute file resou
=> Add url to attribute file resource

packages/Webkul/Admin/src/Resources/views/components/attributes/view/date.blade.php
=> Date time format

packages/Webkul/Email/src/Helpers/Attachment.php
=> chore: update Attachment.php

packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
Update mail view render event.
=> Update mail view render event.

packages/Webkul/Admin/src/Resources/views/components/activities/actions/file.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/mail.blade.php
=> Lead actions ui.

packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
=> Mail view page refactor.

packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php
refactor the quotes edit and create page.
=> refactor the quotes edit and create page.

.env.example, packages/Webkul/Admin/src/Resources/views/quotes/pdf.blade.php
=> issue #1611 fixed.

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/activities/actions/activity/participants.blade.php
activities participants dark mode ui fixed.
=> activities participants dark mode ui fixed.

packages/Webkul/Admin/src/DataGrids/Lead/LeadDataGrid.php, packages/Webkul/Admin/src/DataGrids/Product/ProductDataGrid.php, packages/Webkul/Admin/src/DataGrids/Quote/QuoteDataGrid.php, packages/Webkul/Admin/src/Helpers/Reporting/Organization.php, packages/Webkul/Admin/src/Helpers/Reporting/Person.php, packages/Webkul/Admin/src/Helpers/Reporting/Product.php, packages/Webkul/Lead/src/Database/Migrations/2021_09_30_154222_alter_lead_pipeline_stages_table.php, packages/Webkul/Lead/src/Database/Migrations/2021_09_30_161722_alter_leads_table.php
use variable instead of calling every time of use db table prefix.
=> use variable instead of calling every time of use db table prefix.

CHANGELOG.md
=> Change log updated.

packages/Webkul/Admin/src/Resources/views/quotes/pdf.blade.php
=> Quote pdf download error fix.

packages/Webkul/Admin/src/Http/Controllers/Lead/LeadController.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
=> Issue #1594 fixed.

packages/Webkul/Admin/src/Http/Resources/StageResource.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
fix leadn kanban sort order issue.
=> fix lead kanban sort order issue.

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/index.blade.php
=> fix datagrid shimmers.

packages/Webkul/Admin/src/DataGrids/Settings/AttributeDataGrid.php
=> Issue #1660 fixed.

packages/Webkul/Admin/src/Resources/views/components/attributes/view/text.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/view/textarea.blade.php
=> Issue #1655 fixed.

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
[FIX] RTL View -> Admin Profile Dropdown is having UI and Translation issue. #1667
=> [FIX] RTL View -> Admin Profile Dropdown is having UI and Translation issue.

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php
activities datagrid total counts.
=> activities datagrid total counts.

composer.json
Update composer for devlopment phase.
=> Update composer for devlopment phase.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/tags.blade.php
=> [2.0] Issue #1690 fixed.

CHANGELOG.md, packages/Webkul/Core/src/Core.php
**BUGS:**
Update Changelog For 2.0.3
Update Version in Core.php
=> Update Changelog For 2.0.3 Update Version in Core.php

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/datetime.blade.php
**BUGS:**
Fixed date time attribute component issue
=> Fixed date time attribute component issue

packages/Webkul/Admin/src/Resources/views/settings/groups/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/types/index.blade.php
**BUGS:**
Fixed setting section modal issues
=> Fixed setting section modal issues

packages/Webkul/Admin/src/Resources/views/leads/view/stages.blade.php
=> Fixed issue #1834

packages/Webkul/Admin/src/Resources/views/settings/sources/index.blade.php
=> Fixed issue #1760

packages/Webkul/Admin/src/DataGrids/Settings/UserDataGrid.php
=> Fixed issue #1767

packages/Webkul/Admin/src/Resources/views/settings/pipelines/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/pipelines/edit.blade.php
=> Fixed issue #1764

packages/Webkul/Admin/src/Helpers/Reporting/Lead.php
**BUGS:**
Fixed total won and total lost revenue.
=> Fixed total won and total lost revenue

packages/Webkul/Email/src/Helpers/Htmlfilter.php, packages/Webkul/Email/src/Helpers/Parser.php, packages/Webkul/Email/src/Repositories/EmailRepository.php
=> Fix Pint Issue.

packages/Webkul/Admin/src/DataGrids/Settings/UserDataGrid.php, packages/Webkul/Admin/src/Resources/views/components/attributes/view/text.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1782

packages/Webkul/Admin/src/Resources/views/components/dropdown/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/tags/index.blade.php
=> ⬆️ Some code refined.

packages/Webkul/Admin/src/Http/Controllers/Settings/GroupController.php, packages/Webkul/Admin/src/Resources/views/settings/groups/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1759

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
Fixed Saved Filter Issue #1801
=> 🛠️ [v2.0] : Fixed Saved Filter Issue #1801

packages/Webkul/Admin/src/Resources/views/dashboard/index/open-leads-by-states.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1798

packages/Webkul/Admin/src/Http/Controllers/Settings/RoleController.php, packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1761

packages/Webkul/Admin/src/Resources/views/settings/pipelines/edit.blade.php
=> ⬆️ [v2.0] : Added Suggestion #1763

packages/Webkul/Attribute/src/Repositories/AttributeRepository.php
=> 🛠️ [v2.0] : Fixed Issue #1914

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/create.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1917

packages/Webkul/Email/src/Helpers/Parser.php
=> ☑️ Fixed Pint Issue.

packages/Webkul/Email/src/Helpers/Htmlfilter.php
=> ☑️ Fixed Pint Issue

packages/Webkul/Admin/src/Resources/views/contacts/persons/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/edit.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1785

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/address.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/view.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view.blade.php, packages/Webkul/Admin/src/Resources/views/products/view.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1784

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1741

packages/Webkul/Contact/src/Repositories/PersonRepository.php
=> 🛠️ [v2.0] : Fixed Issue #1794

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1799

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1819

packages/Webkul/Installer/src/Resources/views/installer/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1755

packages/Webkul/Admin/src/Http/Controllers/Settings/TagController.php, packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1758

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php
=> 🛠️ [v2.0] : Fixed Issue #1792

packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1796

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php
=> 🛠️  [v2.0] : Fixed Issue #1808

packages/Webkul/Quote/src/Repositories/QuoteItemRepository.php
=> 🛠️ [v2.0] : Fixed Issue #1804

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1833

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1802

packages/Webkul/Admin/src/Resources/views/leads/index/kanban.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1812

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
**BUGS:**
Fixed issue #1806 (Update Button in Filters Not Visible in Dark Theme and Empty image Cross icon )
=> Fixed issue #1806 (Update Button in Filters Not Visible in Dark Theme and Empty image Cross icon )

packages/Webkul/WebForm/src/Resources/views/settings/web-forms/controls.blade.php
**BUGS:**
Fixed issue #1846 (Placeholder Entries Not Visible in Webform Preview Page)
=> Fixed issue #1846 (Placeholder Entries Not Visible in Webform Preview Page)

packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1825

packages/Webkul/Admin/src/Resources/views/products/view/inventory.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1828

packages/Webkul/Automation/src/Services/WebhookService.php
=> 🛠️ [v2.0] : Fixed issue #1868

packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
=> 🛠️ [v2.0] : Fixed issue #1800

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1791

packages/Webkul/Admin/src/Resources/views/activities/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1793

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/vi/app.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1820

packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
=> 🛠️ [v2.0] : Fixed Issue #1829

packages/Webkul/Admin/src/Http/Controllers/Settings/RoleController.php
=> 🛠️ [v2.0] : Fixed issue in roles.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php
**BUGS:**
Fixed Inline text type component large content issue
=> Fixed Inline text type component large content issue

CHANGELOG.md
**BUGS:**
Changelog for v2.0.5
=> Changelog for v2.0.5

packages/Webkul/Admin/src/Resources/views/products/view.blade.php
**BUGS:**
Fixed product name and sku UI
=> Fixed product name and sku UI

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php
**BUGS:**
Fixed Inline update issue
=> Fixed Inline update issue

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php
**BUGS:**
Fixed issue #1961 (Activity Schedule From and  Schedule To)
=> Fixed issue #1961 (Activity Schedule From and  Schedule To) 

packages/Webkul/Admin/src/Resources/assets/css/app.css, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
**BUGS:**
Fixed issue #1970 (Transparent button issue)
=> Fixed issue #1970 (Transparent button issue)

packages/Webkul/Admin/src/Resources/assets/js/plugins/vee-validate.js, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/address.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/organizations/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/edit.blade.php
**BUGS:**
Update postcode validation and fix postcode validation issues
=> Update postcode validation and fix postcode validation issues

.github/PULL_REQUEST_TEMPLATE.md
Update Formatted Pull Request Template.
=> 🆕 Update Formatted Pull Request Template.

packages/Webkul/Admin/src/Resources/views/components/layouts/anonymous.blade.php
=> Fixed brand color issue.

packages/Webkul/Admin/src/Routes/Admin/products-routes.php
Fixed Route issue in products.
=> Fixed Route issue in products.

packages/Webkul/Admin/src/Http/Controllers/Settings/RoleController.php
=> Fixed role creates issue

packages/Webkul/Admin/tests/e2e-pw/tests/mail/draft.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/mail/outbox.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/mail/sent.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/mail/trash.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/automation/events.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/lead/types.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/user/users.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/users.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/warehouses/warehouse.spec.ts, packages/Webkul/Admin/tests/e2e-pw/utils/components.ts, packages/Webkul/Admin/tests/e2e-pw/utils/faker.ts
=> Adding more  test cases

packages/Webkul/Admin/src/Resources/lang/ar/app.php, packages/Webkul/Admin/src/Resources/lang/en/app.php, packages/Webkul/Admin/src/Resources/lang/es/app.php, packages/Webkul/Admin/src/Resources/lang/fa/app.php, packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/Admin/src/Resources/lang/tr/app.php, packages/Webkul/Admin/src/Resources/lang/vi/app.php, packages/Webkul/Admin/src/Resources/views/settings/marketing/events/index.blade.php
Fix issue in Event Save button.
=> Fix issue in Event save button.

packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php, packages/Webkul/Admin/src/Resources/views/settings/marketing/campaigns/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/edit.blade.php, packages/Webkul/Admin/tests/e2e-pw/tests/settings/user/groups.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/user/users.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/warehouses/warehouse.spec.ts, packages/Webkul/Admin/tests/e2e-pw/utils/faker.ts, packages/Webkul/WebForm/src/Resources/views/components/form/control-group/control.blade.php
Added for in label and use components in forms.
Fix the user test case.
Fix the warehouse test case.
Added group test cases for fixing the fail testcase on users.
=> Added for in label and use component in forms.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/tags.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
**BUGS:**
Fixed issue #1972 (Email sent without email address)
=> Fixed issue #1972 (Email sent without email address)

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php, packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/mega-search.blade.php, packages/Webkul/Admin/src/Resources/views/components/layouts/header/mobile/mega-search.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/datagrid/table/head.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/datagrid/toolbar.blade.php, packages/Webkul/Admin/src/Resources/views/components/shimmer/leads/index/kanban/toolbar.blade.php, packages/Webkul/Admin/src/Resources/views/configuration/edit.blade.php, packages/Webkul/Admin/src/Resources/views/contacts/persons/view/attributes.blade.php, packages/Webkul/Admin/src/Resources/views/leads/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/attributes.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/person.blade.php, packages/Webkul/Admin/src/Resources/views/leads/view/stages.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/products/view/attributes.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/contact-information.blade.php, packages/Webkul/Admin/src/Resources/views/settings/warehouses/view/general-information.blade.php
=> Mobile responsive

README.md
=> Fixed Issue #2061

packages/Webkul/Admin/src/Resources/views/products/create.blade.php, packages/Webkul/Admin/src/Resources/views/products/edit.blade.php
Fixed attributes listing in the product
=> Fixed attributes listing in the product

packages/Webkul/Contact/src/Repositories/PersonRepository.php
=> Fixed Issue #2060

packages/Webkul/Admin/src/Resources/views/components/layouts/header/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/modal/index.blade.php
Fixed menu and modal padding issue
=> Fixed menu and modal padding issue

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php
Reverting the lookup component changes of this [commit](https://github.com/krayin/laravel-crm/commit/9c1752fa9b286baa1f06a5f63c139c3b9f98737c).
=> Reverting the lookup component changes.

packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php
Adjustments based on typical Brazilian sales language.
=> pt_BR Adjustments based on typical Brazilian sales language.

packages/Webkul/Admin/src/Resources/views/components/attributes/edit/price.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/index.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/web-forms/create.blade.php, packages/Webkul/Installer/src/Database/Seeders/Attribute/AttributeSeeder.php
=> Fixing lead validations #2064.

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/index.blade.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/create.blade.php, packages/Webkul/Admin/src/Resources/views/quotes/edit.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/create.blade.php, packages/Webkul/Admin/src/Resources/views/settings/workflows/edit.blade.php
=> 🪶  (Add new) feature in the lookup component.

packages/Webkul/Admin/src/Resources/lang/pt_BR/app.php, packages/Webkul/DataTransfer/src/Resources/lang/pt_BR/app.php, packages/Webkul/Installer/src/Resources/lang/pt_BR/app.php, packages/Webkul/WebForm/src/Resources/lang/pt_BR/app.php
Adjustments and translations for pt_BR. Adjustments based on typical Brazilian sales language.
=> Adjustments and translations for pt_BR

packages/Webkul/Admin/src/Resources/views/leads/common/contact.blade.php
=> Fixing lookup issue.

packages/Webkul/Admin/tests/e2e-pw/tests/lead.spec.ts
=> Added Lead test case.

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/tags.blade.php, packages/Webkul/Admin/src/Resources/views/mail/index.blade.php, packages/Webkul/Admin/src/Resources/views/mail/view.blade.php
Fixing email tags validation issue.
=> Fixing email tags validation issue.

packages/Webkul/Admin/src/Resources/views/components/activities/index.blade.php
Fixed Product View page issue.
=> Fixed Product View page issue.

packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
Improve mail layout for responsiveness and readability. #1967
=> Improve mail layout for responsiveness and readability.

packages/Webkul/Admin/src/Http/Controllers/Contact/Persons/PersonController.php, packages/Webkul/Admin/src/Http/Requests/LeadForm.php, packages/Webkul/Admin/src/Resources/views/components/attributes/edit/lookup.blade.php, packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/text.blade.php, packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php, packages/Webkul/Admin/src/Resources/views/leads/create.blade.php, packages/Webkul/Contact/src/Repositories/PersonRepository.php, packages/Webkul/Lead/src/Repositories/LeadRepository.php
Fix the lead issue with new person details.
=> Fix the lead issue with new person details.

.github/workflows/admin_playwright_tests.yml, packages/Webkul/Admin/tests/e2e-pw/playwright.config.ts, packages/Webkul/Admin/tests/e2e-pw/tests/auth.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/contacts/organization.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/contacts/person.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/lead.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/product.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/quotes.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/automation/events.spec.ts, packages/Webkul/Admin/tests/e2e-pw/tests/settings/user/users.spec.ts, packages/Webkul/Admin/tests/e2e-pw/utils/faker.ts
=> test: added testcases
