krayin/laravel-crm

packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/lookup.blade.php

**Reference Issues/PR**
#28 
**What is reason of this issue ?**
In lookup blade/view file , there is JavaScript variable called "search_route" which is responsible for getting data from server(AJAX REQUEST] on keyup of organization input field while creating lead. It was creating wrong URL that is problem. 
**Solution**
I have updated lookup blade/view file to solve url issue
Replaced below line of code
`search_route: this.searchRoute ? this.searchRoute : "{{ route('admin.settings.attributes.lookup') }}" + this.attribute['id'],`
with 
`search_route: this.searchRoute ? this.searchRoute : "{{ route('admin.settings.attributes.lookup') }}" + "/" + this.attribute['id'],`
**Other comment**
I have seen same code/issue on tags view file, Let me know if that is also issue.
`search_route: …

Routes link fix in lookup view file

---

packages/Webkul/Admin/src/DataGrids/Activity/ActivityDataGrid.php

Link: https://github.com/krayin/laravel-crm/issues/407
- Already one tab filter is by default selected i.e. `All`.
- So removed active from the `This Month`.

Removed Active From This Month

---

packages/Webkul/Admin/src/Database/Seeders/AttributeSeeder.php

Link: https://github.com/krayin/laravel-crm/issues/413

Attribute table seeder fixed #413

---

packages/Webkul/Admin/src/Resources/views/settings/attributes/edit.blade.php

- https://github.com/krayin/laravel-crm/issues/463
- Disabled required field for system attributes from the frontend.

Disabled required field for system attributes from the frontend #463

---

packages/Webkul/Admin/src/DataGrids/Setting/TagDataGrid.php

**BUGS:**
Fix bug stored XSS in Tags
Disclosure: https://huntr.dev/bounties/a11bca75-f8a8-449d-82cd-d463bfd84f72
The nameTag value is retrieved and used without any filter to prevent XSS execution. PHP provides a built-in `htmlspecialchars` function to do just that. [https://www.php.net/manual/en/function.htmlspecialchars.php](https://www.php.net/manual/en/function.htmlspecialchars.php)

Add `htmlspecialchars` function for nameTag

---

packages/Webkul/Admin/src/Exceptions/Handler.php
packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php

**BUGS:** 
Fixed issue #936
Translate all warning message

Fixed issue #936

---

packages/Webkul/UI/src/DataGrid/DataGrid.php

It become hard to manage leads and is useless to see the first lead first when you work with them.   If I have 1000 leads and want to display just 20 leads per page I have to pros nex page 20 times, there is no go to page 20 function also. Now the only use is to make sure you don't forget you're first client.
**BUGS:**

 Change leads order start form the first to the lasst

---

packages/Webkul/Admin/src/Http/Middleware/Bouncer.php

**BUGS:**
#1071
>Redirect to the login page with a flash message if the user has not any permission.

Issue #1071 fixed

---

packages/Webkul/WebForm/src/Http/routes.php

We have fixed the issue when the admin is clicking on the web form inside the settings, then the app locale is automatically changing to English.
path: packages/Webkul/WebForm/src/Http/routes.php line no. 2

issue #1123 fixed

---

packages/Webkul/Admin/src/DataGrids/Settings/PipelineDataGrid.php
packages/Webkul/Admin/src/DataGrids/Settings/TagDataGrid.php
packages/Webkul/Admin/src/DataGrids/Settings/UserDataGrid.php
packages/Webkul/Admin/src/Http/Controllers/Settings/TagController.php
packages/Webkul/Admin/src/Http/Controllers/Settings/UserController.php
packages/Webkul/Admin/src/Http/routes.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/views/common/custom-attributes/edit/textarea.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/organizations/edit.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/organizations/index.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/persons/create.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/persons/edit.blade.php
packages/Webkul/Admin/src/Resources/views/sessions/forgot-password.blade.php
packages/Webkul/Admin/src/Resources/views/sessions/login.blade.php
packages/Webkul/Admin/src/Resources/views/sessions/reset-password.blade.php
packages/Webkul/Admin/src/Resources/views/settings/pipelines/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/roles/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/roles/edit.blade.php
packages/Webkul/Admin/src/Resources/views/settings/tags/index.blade.php
packages/Webkul/Admin/src/Resources/views/settings/users/index-old.blade.php
packages/Webkul/Admin/src/Resources/views/settings/users/index.blade.php
packages/Webkul/Admin/src/Routes/settings-routes.php
routes/breadcrumbs.php

Updated Tag and User Page 

---

packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/select.blade.php
packages/Webkul/Admin/src/Resources/views/components/lookup/index.blade.php
packages/Webkul/Admin/src/Resources/views/leads/common/products.blade.php
packages/Webkul/Admin/src/Resources/views/leads/edit.blade.php
packages/Webkul/Admin/src/Resources/views/leads/view/products.blade.php

ui issues.

---

packages/Webkul/Admin/src/Resources/views/components/attributes/view/date.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/date.blade.php
packages/Webkul/Admin/src/Resources/views/leads/index/kanban/filter.blade.php

Inline component issues

---

packages/Webkul/Admin/src/Resources/views/settings/web-forms/create.blade.php

Fixes #1614 - Ensure attribute options are visible when creating lead webforms
**BUGS:**
When creating a lead webform without enabling the "lead toggle" button, the attribute options are not displayed. This issue arises because the form logic doesn't correctly handle cases where the lead toggle is disabled.
This PR ensures that the attribute options are always visible, regardless of the lead toggle state, thus fixing the issue where users couldn't see necessary attributes for the webform.

Issue #1614 fixed

---

packages/Webkul/Admin/src/Resources/lang/ar/app.php
packages/Webkul/Admin/src/Resources/lang/en/app.php
packages/Webkul/Admin/src/Resources/lang/es/app.php
packages/Webkul/Admin/src/Resources/lang/fa/app.php
packages/Webkul/Admin/src/Resources/lang/tr/app.php
packages/Webkul/Admin/src/Resources/views/components/avatar/index.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/persons/view/organization.blade.php

persons view page avatar and organization edit button. #1619

persons view page avatar and organization edit button.

---

packages/Webkul/Admin/src/Resources/views/components/datagrid/table.blade.php
packages/Webkul/Admin/src/Resources/views/components/datagrid/toolbar/filter.blade.php

fix div can not be child of p warning into console.

fix div can not be child of p.

---

packages/Webkul/Email/src/Helpers/Parser.php

Fix an error where the email parser would fail when processing certain email parts due to missing 'from' headers in multipart messages.
When processing multipart email messages, some parts (particularly nested ones) don't contain their own headers. This was causing an "Undefined array key 'from'" error when the code attempted to access the 'from' header directly.
- Added header existence validation before accessing the 'from' field
- Implemented fallback to parent part headers when child part headers are missing
- Added graceful continuation of processing when headers cannot be found
```php
// Before
$part_from_sender = is_array($part['headers']['from']) ? $part['headers']['from'][0] : $part['headers']['from'];
// After
if (empty($part['headers']) || !isset($part['headers']['from'])) { …
```

Undefined array key 'from' error when processing certain emails

---

packages/Webkul/Email/src/Helpers/Htmlfilter.php

Updated `tln_tagprint` method to use modern PHP iteration syntax, removing deprecated `each()` function.
- Replaced `each()` with `foreach` loop
- Simplified array population method
- Maintained original method logic
- Ensures compatibility with PHP 7.2+ and PHP 8.0+
```php
// Before
while ([$attname, $attvalue] = each($attary)) {
array_push($atts, "$attname=$attvalue");
}
// After
foreach ($attary as $attname => $attvalue) {
$atts[] = "$attname=$attvalue";
}
```
- `each()` function is deprecated and removed in newer PHP versions
- `foreach` provides a more modern and readable way to iterate arrays
- `$atts[]` is a more concise way to add elements to an array compared to `array_push()`
- Improves code maintainability and compatibility

Modernization: Replace Deprecated `each()` Function in `tln_tagprint`

---

packages/Webkul/Email/src/Helpers/Htmlfilter.php

Fixed a potential type error when checking for whitespace in email parsing.
- Modified `tln_skipspace` method to handle string inputs safely
- Prevents "count() must be of type Countable|array" error
- Maintains original logic of skipping whitespace
```php
// Before
if (count($matches[1])) {
$count = strlen($matches[1]);
$offset += $count;
}
// After
if (!empty($matches[1])) {
$count = strlen($matches[1]);
$offset += $count;
}
```
- Original code assumed $matches[1] would always be an array
- New implementation checks for non-empty value before processing
- Improves error handling and type safety

Bug Fix: Prevent Count Error in tln_skipspace Method

---

packages/Webkul/Email/src/Helpers/Htmlfilter.php

Fixed an issue with array_walk callback by using the class method as a callback.
- Modified the code to use `[$this, 'tln_casenormalize']` instead of a global function call
- Ensures the case normalization method is correctly called within the class context
- Prevents undefined function errors during email parsing
```php
// Before
@array_walk($tag_list, 'tln_casenormalize');
@array_walk($rm_tags_with_content, 'tln_casenormalize');
@array_walk($self_closing_tags, 'tln_casenormalize');
// After
@array_walk($tag_list, [$this, 'tln_casenormalize']);
@array_walk($rm_tags_with_content, [$this, 'tln_casenormalize']);
@array_walk($self_closing_tags, [$this, 'tln_casenormalize']);

Bug Fix: Resolve Callback Issue in Email Parsing

---

packages/Webkul/Email/src/Helpers/Htmlfilter.php

Updated `tln_fixatts` method to use modern PHP iteration syntax, removing deprecated `each()` function.
- Replaced `each()` with `foreach` loop
- Added type safety for input array
- Maintained original method logic
- Ensures compatibility with PHP 7.2+ and PHP 8.0+
- Improved loop control with `continue 2`
```php
// Before
while ([$attname, $attvalue] = each($attary)) {
// Processing logic
}
// After
foreach ($attary as $attname => $attvalue) {
// Processing logic with continue 2
}
```
- each() function is deprecated and removed in newer PHP versions
- foreach provides a more modern and readable way to iterate arrays
- continue 2 ensures proper loop control when removing attributes
- Immediately exits both inner and outer loops
- Prevents unnecessary iteration after attribute removal
- …

Modernization: Replace Deprecated `each()` Function

---

packages/Webkul/Admin/src/Helpers/Reporting/Lead.php
packages/Webkul/Admin/src/Resources/views/components/charts/bar.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/over-all.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-sources.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue-by-types.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/revenue.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/top-persons.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/top-selling-products.blade.php
packages/Webkul/Admin/src/Resources/views/dashboard/index/total-leads.blade.php
packages/Webkul/Admin/src/Resources/views/products/create.blade.php

🛠️ [v2.0] : Fixed Issue #1787

---

packages/Webkul/Admin/src/Resources/views/activities/edit.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/email.blade.php
packages/Webkul/Admin/src/Resources/views/contacts/organizations/create.blade.php

🛠️ [v2.0] : Fixed Issue #1822

---

packages/Webkul/Admin/src/Http/Controllers/Settings/AttributeController.php
packages/Webkul/Admin/src/Resources/views/components/attributes/view/file.blade.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/inline/file.blade.php
packages/Webkul/Admin/src/Resources/views/products/edit.blade.php

🛠️ [v2.0] : Fixed Issue  #1742

---

packages/Webkul/Attribute/src/Repositories/AttributeRepository.php

Modified the query for users with 'individual' view permission to include the 'get()' method. This ensures the query returns the result as expected. This fixes the issue with users with permission individual to see options in dropdown while creating leads preventing potential issues with missing results.
**BUGS:**
> No options in drop down for create leads sections for user with individual permission.

This PR updates the query in the user repository to include a get() method, ensuring the query results are fetched in AttributeRepository.php

---

packages/Webkul/Admin/src/Config/core_config.php
packages/Webkul/Admin/src/DataGrids/Mail/EmailDataGrid.php
packages/Webkul/Admin/src/Resources/views/components/form/control-group/controls/tags.blade.php
packages/Webkul/Admin/src/Resources/views/mail/index.blade.php
packages/Webkul/Admin/src/Resources/views/mail/view.blade.php

https://github.com/krayin/laravel-crm/issues/1983
https://github.com/krayin/laravel-crm/issues/1982
https://github.com/krayin/laravel-crm/issues/1981
https://github.com/krayin/laravel-crm/issues/1976
https://github.com/krayin/laravel-crm/issues/1977
https://github.com/krayin/laravel-crm/issues/1971
https://github.com/krayin/laravel-crm/issues/1969
https://github.com/krayin/laravel-crm/issues/1968

:wrench: fix: email issues

---

packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php
packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/edit.blade.php

Remove mandatory field from process in queue button.
Issue No. #2064 -> Point Number 6.

Remove mandatory field from process in queue button.
